steps:
  # Step 1: Build the Docker image (if necessary)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/de-fi-app:latest'
      - '.'

  # Step 2: Push the Docker image to Google Container Registry (if necessary)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/de-fi-app:latest'

  # Step 3: Upload DAGs to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - './dags/*.py'
      - 'gs://europe-west1-de-fi-analytic-102096ac-bucket/dags/'

  # Step 4: Upload additional scripts to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - './scripts/ingest_data.py'
      - 'gs://europe-west1-de-fi-analytic-102096ac-bucket/dags/'

images:
  - 'gcr.io/$PROJECT_ID/de-fi-app:latest'
