steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/de-fi-app:$SHORT_SHA'
      - '.'

  # Step 2: Push the Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/de-fi-app:$SHORT_SHA'

images:
  - 'gcr.io/$PROJECT_ID/de-fi-app:$SHORT_SHA'

options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

service_account: your-service-account@your-project.iam.gserviceaccount.com
